language: rust
cache: cargo
jobs:
  include:
    - os: linux
      rust: stable
    - os: osx
      rust: stable
    - os: windows
      rust: stable-msvc

script:
  - cargo build --verbose
  - cargo test --verbose
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      rustup component add clippy
      cargo clippy --verbose
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ./msgfmt.sh
      if [ -n "$(git status -s)" ]; then
        echo "If this fails, the lang/*.mo files are out of date."
        echo "Run ./msgfmt.sh to fix this."
        exit 1
      fi
    fi
