sudo: false
language: rust
env: RUSTFLAGS="-C link-dead-code"
matrix:
    include:
        - rust: stable
        - rust: beta
        - rust: nightly
    allow_failures:
        - rust: beta
        - rust: nightly
    fast_finish: true

# kcov dependencies
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - |
      cargo install --force cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH

script:
    - cargo build --verbose
    - cargo test --verbose
    - |
        if [ $TRAVIS_RUST_VERSION == "nightly" ]; then
            cargo install clippy && cargo clippy -- -Dclippy
        fi

after_success:
    - cargo coveralls
