language: rust
cache: cargo
jobs:
  include:
    - os: linux
      rust: stable
    - os: osx
      rust: stable
    - os: windows
      rust: stable-msvc

script:
  - cargo build --verbose
  - cargo test --verbose
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      rustup component add clippy
      cargo clippy --verbose
    fi
