[package]
name = "portier_broker"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
build = "build.rs"
description = "Reference implementation of the Portier broker protocol"
homepage = "http://portier.io"
repository = "https://github.com/portier/portier-broker"
readme = "README.rst"
license = "MIT/Apache-2.0"

[[bin]]
name = "portier-broker"
path = "src/main.rs"

[build-dependencies]
glob = "0.2.11"

[dependencies]
docopt = "0.6.86"
emailaddress = "0.4.0"
env_logger = "0.3.5"
futures = "0.1.14"
gettext = "0.2.0"
hyper = "0.11.2"
lettre = "=0.6.1"
log = "0.3.6"
mustache = "0.8.0"
openssl = "0.7.14"
rand = "0.3.15"
redis = "0.8.0"
rustc-serialize = "0.3.22"
serde = "0.9.7"
serde_derive = "0.9.7"
serde_json = "0.9.6"
time = "0.1.35"
tokio-core = "0.1.9"
toml = "0.3.0"
url = "1.5.1"
