[package]
name = "portier_broker"
version = "0.3.1"
authors = ["The Portier project contributors"]
description = "Reference implementation of the Portier broker protocol"
homepage = "http://portier.io"
repository = "https://github.com/portier/portier-broker"
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[features]
default = ["redis", "rusqlite", "lettre_smtp"]
insecure = []
lettre_smtp = ["lettre", "lettre_email"]

[[bin]]
name = "portier-broker"
path = "src/main.rs"

[dependencies]
accept-language = "2.0.0"
base64 = "0.12.0"
bytes = "0.5.4"
docopt = "1.1.0"
envy = "0.4.1"
err-derive = "0.2.4"
futures-util = "0.3.4"
gettext = "0.4.0"
headers = "0.3.2"
http = "0.2.1"
hyper = "0.13.5"
hyper-staticfile = "0.5.2"
hyper-tls = "0.4.1"
idna = "0.2.0"
lazy_static = "1.4.0"
listenfd = "0.3.3"
matches = "0.1.8"
mustache = "0.9.0"
native-tls = "0.2.4"
percent-encoding = "2.1.0"
ring = "0.16.12"
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.52"
toml = "0.5.6"

[dependencies.lettre]
optional = true
version = "0.9.3"

[dependencies.lettre_email]
optional = true
version = "0.9.4"

[dependencies.log]
version = "0.4.8"
features = ["std", "release_max_level_info"]

[dependencies.redis]
optional = true
version = "0.15.1"
features = ["tokio-rt-core"]

[dependencies.rusqlite]
optional = true
version = "0.23.1"
features = ["bundled"]

[dependencies.tokio]
version = "0.2.19"
features = ["fs", "macros", "process", "rt-threaded", "sync", "time"]

[dependencies.url]
version = "2.1.1"
features = ["serde"]

[target.'cfg(unix)'.dependencies]
sd-notify = "0.1.1"
