[package]
name = "ladaemon"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]

[dependencies]
emailaddress = "*"
hyper = "*"
iron = "*"
lettre = "*"
openssl = "0.7"
rand = "*"
redis = "*"
router = "*"
rustc-serialize = "*"
serde_json = "*"
time = "*"
url = "*"
urlencoded = "*"
