[package]
name = "portier_broker"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
build = "build.rs"
description = "Reference implementation of the Portier broker protocol"
homepage = "http://portier.io"
repository = "https://github.com/portier/portier-broker"
readme = "README.rst"
license = "MIT/Apache-2.0"

[[bin]]
name = "portier-broker"

[build-dependencies]
glob = "0.2.11"
serde_codegen = "0.8.0"

[dependencies]
docopt = "0.6.86"
emailaddress = "0.4.0"
env_logger = "0.3.5"
hyper = "0.9.14"
iron = "0.4.0"
lettre = "0.6.1"
log = "0.3.6"
mustache = "0.8.0"
openssl = "0.7.14"
rand = "0.3.15"
redis = "0.8.0"
router = "0.4.0"
rustc-serialize = "0.3.22"
serde = "0.8.21"
serde_json = "0.8.4"
staticfile = { version = "0.3.1", features = ["cache"] }
time = "0.1.35"
toml = { version = "0.2.1", default-features = false, features = ["serde"]}
url = "1.2.4"
urlencoded = "0.4.1"
gettext = "0.2.0"
