[package]
name = "portier_broker"
version = "0.2.0"
authors = ["The Portier project contributors"]
description = "Reference implementation of the Portier broker protocol"
homepage = "http://portier.io"
repository = "https://github.com/portier/portier-broker"
readme = "README.rst"
license = "MIT/Apache-2.0"
edition = "2018"

[features]
default = []
insecure = []

[[bin]]
name = "portier-broker"
path = "src/main.rs"

[dependencies]
accept-language = "2.0.0"
base64 = "0.11.0"
bytes = "0.5.3"
docopt = "1.1.0"
env_logger = "0.7.1"
futures-util = "0.3.1"
gettext = "0.4.0"
headers = "0.3.0"
http = "0.2.0"
hyper = "0.13.1"
hyper-staticfile = "0.5.1"
hyper-tls = "0.4.1"
idna = "0.2.0"
lettre = "0.9.2"
lettre_email = "0.9.2"
listenfd = "0.3.3"
log = "0.4.8"
matches = "0.1.8"
mustache = "0.9.0"
native-tls = "0.2.3"
percent-encoding = "2.1.0"
redis = { version = "0.15.1", features = ["tokio-rt-core"] }
ring = "0.16.9"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
tokio = { version = "0.2.9", features = ["time", "macros"] }
toml = "0.5.6"
url = "2.1.1"

[target.'cfg(unix)'.dependencies]
sd-notify = "0.1.1"
