[package]
name = "ladaemon"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8.0"

[dependencies]
docopt = "0.6.81"
emailaddress = "0.3.0"
hyper = "0.9.10"
iron = "0.4.0"
lettre = "0.5.1"
openssl = "0.7.13"
rand = "0.3.14"
redis = "0.7.0"
router = "0.2.0"
rustc-serialize = "0.3.19"
serde = "0.8.0"
serde_json = "0.8.0"
time = "0.1.35"
url = "1.1.0"
urlencoded = "0.4.0"
