[package]
name = "portier_broker"
version = "0.2.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
build = "build.rs"
description = "Reference implementation of the Portier broker protocol"
homepage = "http://portier.io"
repository = "https://github.com/portier/portier-broker"
readme = "README.rst"
license = "MIT/Apache-2.0"

[features]
default = []
insecure = []

[[bin]]
name = "portier-broker"
path = "src/main.rs"

[build-dependencies]
glob = "0.2.11"

[dependencies]
base64 = "0.8.0"
docopt = "0.8.1"
env_logger = "0.4.3"
futures = "0.1.17"
gettext = "0.2.0"
hyper = "0.11.7"
hyper-staticfile = "0.1.1"
hyper-tls = "0.1.2"
lettre = "0.7.0"
lettre_email = "0.7.0"
log = "0.3.8"
mustache = "0.8.2"
native-tls = "0.1.4"
openssl = "0.9.22"
rand = "0.3.18"
redis = "0.8.0"
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.7"
time = "0.1.38"
tokio-core = "0.1.10"
toml = "0.4.5"
url = "1.6.0"
