[package]
name = "portier_broker"
version = "0.2.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
build = "build.rs"
description = "Reference implementation of the Portier broker protocol"
homepage = "http://portier.io"
repository = "https://github.com/portier/portier-broker"
readme = "README.rst"
license = "MIT/Apache-2.0"

[features]
default = []
insecure = []

[[bin]]
name = "portier-broker"
path = "src/main.rs"

[build-dependencies]
glob = "0.2.11"

[dependencies]
base64 = "0.10.1"
docopt = "1.1.0"
env_logger = "0.6.2"
futures = "0.1.28"
gettext = "0.4.0"
hyper = "0.11.27"
hyper-staticfile = "0.2.0"
hyper-tls = "0.1.4"
idna = "0.1.5"
lettre = "0.9.2"
lettre_email = "0.9.2"
log = "0.4.7"
matches = "0.1.8"
mustache = "0.9.0"
native-tls = "0.2.3"
openssl = "0.10.23"
rand = "0.7.0"
redis = "0.10.0"
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.40"
time = "0.1.42"
tokio-core = "0.1.17"
toml = "0.5.1"
url = "1.7.2"
