name: prep-linux-cross
description: Preparation for Linux cross compiling
inputs:
  targets:
    description: Target triples to prepare for.
    required: true
  packages:
    description: Debian packages to install for all targets.
    required: false
runs:
  using: node12
  main: main.js
