name: Build

on:
  push:
    branches: '**'

jobs:
  checked-build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      mailhog:
        image: mailhog/mailhog:latest
        ports:
          - 1025:1025
          - 8025:8025
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy
        default: true

    - name: Build
      run: cargo build --locked

    - name: Test
      run: cargo test --locked

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Install gettext
      run: sudo apt-get install gettext

    - name: Check translations
      run: |
        ./msgfmt.sh
        if [ -n "$(git status -s)" ]; then
          echo "If this fails, the lang/*.mo files are out of date."
          echo "Run ./msgfmt.sh to fix this."
          exit 1
        fi

    - name: E2E test deps
      run: cd tests/e2e/ && yarn --frozen-lockfile

    - name: E2E test Firefox
      run: cd tests/e2e/ && SELENIUM_BROWSER=firefox ./main.js

    - name: E2E test Chrome
      run: cd tests/e2e/ && SELENIUM_BROWSER=chrome ./main.js

    - name: E2E test Redis
      run: cd tests/e2e/ && TEST_REDIS=1 TEST_ROTATING_KEYS=1 ./main.js

    - name: E2E test SQLite
      run: cd tests/e2e/ && TEST_SQLITE=1 TEST_ROTATING_KEYS=1 ./main.js

  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true

    - name: Build
      run: cargo build --locked

    - name: Test
      run: cargo test --locked
