name: Daily checks

on:
  workflow_dispatch:
  # NOTE: Dependabot runs after this workflow, at 05:00 UTC. By ensuring this
  # workflow runs first, we can perform simple upgrades ahead of Dependabot.
  schedule:
  - cron: '0 3 * * *'

jobs:

  # Creates issues for security advisories.
  audit:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  # Performs simple dependency upgrades automatically.
  # Creates (or updates) a PR, and enables automerging.
  # For larger upgrades, we use Dependabot.
  upgrade-deps:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.46.0'
        profile: minimal
        default: true

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: upgrade-deps-cargo

    - name: Upgrade deps
      run: cargo update

    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        # Use a bot token, so checks run on the PR.
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
        author: 'r-stephank <ghbot@stephank.nl>'
        committer: 'r-stephank <ghbot@stephank.nl>'
        commit-message: "Update Cargo.lock"
        title: "Update Cargo.lock"
        branch: "auto/update-deps"

    - name: Enable automerge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v1
      with:
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
