name: Daily checks

on:
  workflow_dispatch:
  schedule:
  - cron: '0 7 * * *'

jobs:

  # Creates issues for security advisories.
  audit:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # Use the latest release tag, not the main branch.
    # This way, we know when to create a new security release.
    - name: Checkout latest release
      run: |
        set -xe
        tag="$(git ls-remote --sort='-v:refname' origin 'v*' | head -n1 | cut -f2)"
        git fetch origin "$tag"
        git checkout FETCH_HEAD

    - name: Security audit
      uses: stephank/actions-rs-audit-check@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generate-lockfile: false
