name: Deploy

on:
  push:
    branches: [main, stable]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      if: github.repository == 'portier/portier-broker'
      run: |
        curl -X POST \
          -H 'Authorization: token ${{ secrets.BOT_GITHUB_TOKEN }}' \
          -H 'Accept: application/vnd.github.v3+json' \
          https://api.github.com/repos/portier/public-infra/actions/workflows/update_flakes.yml/dispatches \
          -d '{ "ref": "main" }'
